// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	ID               int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                          // 主键
	Username         string `gorm:"column:username;uniqueIndex:username_idx,priority:1;comment:用户名" json:"username"`                       // 用户名
	Password         string `gorm:"column:password;comment:密码" json:"password"`                                                            // 密码
	Step2code        string `gorm:"column:step2code;comment:两步验证码" json:"step2code"`                                                       // 两步验证码
	RoleID           int64  `gorm:"column:role_id;comment:权限ID" json:"role_id"`                                                            // 权限ID
	Status           int64  `gorm:"column:status;comment:状态：1-启用，2-禁用" json:"status"`                                                      // 状态：1-启用，2-禁用
	Comment          string `gorm:"column:comment;comment:备注" json:"comment"`                                                              // 备注
	LastLoggedAt     int64  `gorm:"column:last_logged_at;comment:最后登录时间" json:"last_logged_at"`                                            // 最后登录时间
	LastLoggedIP     string `gorm:"column:last_logged_ip;comment:最后登录IP" json:"last_logged_ip"`                                            // 最后登录IP
	Nickname         string `gorm:"column:nickname;comment:昵称" json:"nickname"`                                                            // 昵称
	DepartmentID     int64  `gorm:"column:department_id;comment:部门ID" json:"department_id"`                                                // 部门ID
	LastLoggedOutAt  int64  `gorm:"column:last_logged_out_at;comment:最后退出登录时间" json:"last_logged_out_at"`                                  // 最后退出登录时间
	TotalLogin       int64  `gorm:"column:total_login;comment:登录次数" json:"total_login"`                                                    // 登录次数
	LoginCount       int64  `gorm:"column:login_count;comment:登录次数" json:"login_count"`                                                    // 登录次数
	GoogleAuthStatus int64  `gorm:"column:google_auth_status;not null;default:2;comment:google验证开启状态：1-启用，2-禁用" json:"google_auth_status"` // google验证开启状态：1-启用，2-禁用
	GoogleAuthSecret string `gorm:"column:google_auth_secret;not null;comment:google验证secret" json:"google_auth_secret"`                   // google验证secret
	//
	gormx.OperationBaseModel
	gormx.Model
	//
	// 关联
	Role       *Role       `gorm:"foreignKey:RoleID;references:ID" json:"role,omitempty"`
	Department *Department `gorm:"foreignKey:DepartmentID;references:ID" json:"department,omitempty"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
