// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"github.com/QuantumShiftX/golib/stores/gormx"
)

const TableNameAdminOperationLog = "admin_operation_logs"

// AdminOperationLog mapped from table <admin_operation_logs>
type AdminOperationLog struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                          // 主键ID
	AdminID         int64  `gorm:"column:admin_id;not null;comment:管理员ID" json:"admin_id"`                                                 // 管理员ID
	AdminUsername   string `gorm:"column:admin_username;not null;comment:管理员账号" json:"admin_username"`                                   // 管理员账号
	Module          string `gorm:"column:module;not null;comment:模块：system-系统管理，user-会员管理，game-游戏管理，fm-财务管理" json:"module"` // 模块：system-系统管理，user-会员管理，game-游戏管理，fm-财务管理
	Content         string `gorm:"column:content;not null;comment:操作内容" json:"content"`                                                   // 操作内容
	Result          int64  `gorm:"column:result;not null;default:1;comment:结果：1-成功，2-失败" json:"result"`                                 // 结果：1-成功，2-失败
	IP              string `gorm:"column:ip;not null;comment:IP地址" json:"ip"`                                                               // IP地址
	APIPath         string `gorm:"column:api_path;not null;comment:API路径" json:"api_path"`                                                  // API路径
	APIRequestParam string `gorm:"column:api_request_param;not null;comment:API请求参数" json:"api_request_param"`                            // API请求参数
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName AdminOperationLog's table name
func (*AdminOperationLog) TableName() string {
	return TableNameAdminOperationLog
}
