// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameCrop = "crops"

// Crop mapped from table <crops>
type Crop struct {
	ID                                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:作物ID" json:"id"`                                                                  // 作物ID
	Name                                string `gorm:"column:name;not null;comment:作物名称" json:"name"`                                                                                   // 作物名称
	Price                               int64  `gorm:"column:price;not null;comment:作物价格（单位：代币）" json:"price"`                                                                          // 作物价格（单位：代币）
	MaturityIncome                      int64  `gorm:"column:maturity_income;not null;comment:成熟收益（代币）" json:"maturity_income"`                                                         // 成熟收益（代币）
	MaturityPeriod                      int64  `gorm:"column:maturity_period;not null;comment:成熟周期（单位：分）" json:"maturity_period"`                                                       // 成熟周期（单位：分）
	WateringFrequency                   int64  `gorm:"column:watering_frequency;default:1;comment:浇水频率（次/天）" json:"watering_frequency"`                                                 // 浇水频率（次/天）
	FertilizingFrequency                int64  `gorm:"column:fertilizing_frequency;default:1;comment:施肥频率（次/天）" json:"fertilizing_frequency"`                                           // 施肥频率（次/天）
	SelfWateringDecreaseTime            int64  `gorm:"column:self_watering_decrease_time;not null;comment:自己每次浇水减少时间（单位：分）" json:"self_watering_decrease_time"`                         // 自己每次浇水减少时间（单位：分）
	SelfWateringDecreasePercentage      int64  `gorm:"column:self_watering_decrease_percentage;not null;comment:自己每次浇水减少百分比（0-100）" json:"self_watering_decrease_percentage"`           // 自己每次浇水减少百分比（0-100）
	SelfFertilizingDecreaseTime         int64  `gorm:"column:self_fertilizing_decrease_time;not null;comment:自己每次施肥减少时间（单位：分）" json:"self_fertilizing_decrease_time"`                   // 自己每次施肥减少时间（单位：分）
	SelfFertilizingDecreasePercentage   int64  `gorm:"column:self_fertilizing_decrease_percentage;not null;comment:自己每次施肥减少百分比（0-100）" json:"self_fertilizing_decrease_percentage"`     // 自己每次施肥减少百分比（0-100）
	FriendWateringDecreaseTime          int64  `gorm:"column:friend_watering_decrease_time;not null;comment:好友每次浇水减少时间（单位：分）" json:"friend_watering_decrease_time"`                     // 好友每次浇水减少时间（单位：分）
	FriendWateringDecreasePercentage    int64  `gorm:"column:friend_watering_decrease_percentage;not null;comment:好友每次浇水减少百分比（0-100）" json:"friend_watering_decrease_percentage"`       // 好友每次浇水减少百分比（0-100）
	FriendFertilizingDecreaseTime       int64  `gorm:"column:friend_fertilizing_decrease_time;not null;comment:好友每次施肥减少时间（单位：分）" json:"friend_fertilizing_decrease_time"`               // 好友每次施肥减少时间（单位：分）
	FriendFertilizingDecreasePercentage int64  `gorm:"column:friend_fertilizing_decrease_percentage;not null;comment:好友每次施肥减少百分比（0-100）" json:"friend_fertilizing_decrease_percentage"` // 好友每次施肥减少百分比（0-100）
	IsAvailable                         int8  `gorm:"column:is_available;not null;default:1;comment:是否上架（1 = 上架, 2 = 下架）" json:"is_available"`                                         // 是否上架（1 = 上架, 2 = 下架）
	Sort                                int64  `gorm:"column:sort;not null;default:1;comment:排序（用于显示顺序）" json:"sort"`                                                                   // 排序（用于显示顺序）
	IsEnabled                           int8 `gorm:"column:is_enabled;not null;default:1;comment:是否启用（1 = 启用, 2 = 禁用）" json:"is_enabled"`                                             // 是否启用（1 = 启用, 2 = 禁用）
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName Crop's table name
func (*Crop) TableName() string {
	return TableNameCrop
}
