// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`              // 主键
	ParentID      int64  `gorm:"column:parent_id;not null;comment:上一级部门ID" json:"parent_id"`                // 上一级部门ID
	Name          string `gorm:"column:name;not null;comment:名称" json:"name"`                               // 名称
	Sort          int64  `gorm:"column:sort;comment:排序" json:"sort"`                                        // 排序
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
