// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                              // 主键ID
	ParentID      int64  `gorm:"column:parent_id;index:idx_departments_parent_id,priority:1;comment:父级部门ID" json:"parent_id"` // 父级部门ID
	Name          string `gorm:"column:name;not null;comment:部门名称" json:"name"`                                               // 部门名称
	Code          string `gorm:"column:code;not null;uniqueIndex:idx_departments_code,priority:1;comment:部门编码" json:"code"`   // 部门编码
	Leader        string `gorm:"column:leader;comment:部门负责人" json:"leader"`                                                   // 部门负责人
	Phone         string `gorm:"column:phone;comment:联系电话" json:"phone"`                                                      // 联系电话
	Email         string `gorm:"column:email;comment:邮箱" json:"email"`                                                        // 邮箱
	Sort          int64  `gorm:"column:sort;comment:排序" json:"sort"`                                                          // 排序
	Status        int64  `gorm:"column:status;default:1;comment:状态: 1-启用, 2-禁用" json:"status"`                                // 状态: 1-启用, 2-禁用
	Remark        string `gorm:"column:remark;comment:备注" json:"remark"`                                                      // 备注
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
