// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameGrowthRule = "growth_rules"

// GrowthRule mapped from table <growth_rules>
type GrowthRule struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                    // 自增主键
	ActionType    int8  `gorm:"column:action_type;not null;default:1;comment:获取成长值的行为类型，1：存款、2：下级存款、3：收获、4：邀请下级、5：每日登录、6：在线时长" json:"action_type"` // 获取成长值的行为类型，1：存款、2：下级存款、3：收获、4：邀请下级、5：每日登录、6：在线时长
	ValueAmount   int64  `gorm:"column:value_amount;not null;comment:行为对应的数值，如存款金额、时长等" json:"value_amount"`                                        // 行为对应的数值，如存款金额、时长等
	GrowthValue   int64  `gorm:"column:growth_value;not null;comment:该行为可获得的成长值数量" json:"growth_value"`                                             // 该行为可获得的成长值数量
	IsEnabled     int8  `gorm:"column:is_enabled;not null;default:1;comment:是否启用（1 = 启用, 2 = 禁用）" json:"is_enabled"`                               // 是否启用（1 = 启用, 2 = 禁用）
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName GrowthRule's table name
func (*GrowthRule) TableName() string {
	return TableNameGrowthRule
}
