// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"github.com/QuantumShiftX/golib/stores/gormx"
	"gorm.io/datatypes"
)

const TableNameIPWhite = "ip_whites"

// IPWhite mapped from table <ip_whites>
type IPWhite struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                         // 主键
	SiteAuthTypes datatypes.JSONSlice[int64] `gorm:"column:site_auth_types;not null;comment:站点权限类型：1-管理后台，2-游戏客户端" json:"site_auth_types"` // 站点权限类型：1-管理后台，2-游戏客户端
	IP            string `gorm:"column:ip;not null;comment:IP地址" json:"ip"`                                            // IP地址
	Comment       string `gorm:"column:comment;not null;comment:备注" json:"comment"`                                    // 备注
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName IPWhite's table name
func (*IPWhite) TableName() string {
	return TableNameIPWhite
}
