// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameLanguage = "languages"

// Language mapped from table <languages>
type Language struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`  // 主键
	LanguageCode string `gorm:"column:language_code;not null;comment:代码" json:"language_code"` // 代码
	LanguageName string `gorm:"column:language_name;not null;comment:名称" json:"language_name"` // 名称
	ChineseNote string `gorm:"column:chinese_note;not null;comment:名称" json:"chinese_note"` // 名称
	Status       int64  `gorm:"column:status;comment:状态" json:"status"`                        // 主键
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName Language's table name
func (*Language) TableName() string {
	return TableNameLanguage
}
