// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameMenu = "menus"

// Menu mapped from table <menus>
type Menu struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`              // 主键
	Title          string `gorm:"column:title;not null;comment:名称" json:"title"`                             // 名称
	ParentID       int64  `gorm:"column:parent_id;not null;comment:上级菜单" json:"parent_id"`                   // 上级菜单
	Path           string `gorm:"column:path;not null;comment:路由" json:"path"`                               // 路由
	Redirect       string `gorm:"column:redirect;not null;comment:重定向" json:"redirect"`                      // 重定向
	Identification string `gorm:"column:identification;not null;comment:唯一标识" json:"identification"`         // 唯一标识
	Icon           string `gorm:"column:icon;not null;comment:图标" json:"icon"`                               // 图标
	Type           int64  `gorm:"column:type;not null;comment:类型：1-菜单,2-按钮" json:"type"`                          // 类型：1-菜单
	Component      string `gorm:"column:component;not null;comment:组件" json:"component"`                     // 组件
	Status         int64  `gorm:"column:status;not null;default:1;comment:状态：1-正常,2-禁用" json:"status"`            // 状态：1-正常
	Sort           int64  `gorm:"column:sort;not null;comment:排序字段" json:"sort"`                             // 排序字段
	APIPath        string `gorm:"column:api_path;not null;comment:API路径" json:"api_path"`                    // API路径
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
