// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import (
	"github.com/QuantumShiftX/golib/stores/gormx"
	"time"
)

const TableNameUserProfile = "user_profiles"

// UserProfile mapped from table <user_profiles>
type UserProfile struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                   // 主键
	UserID         int64     `gorm:"column:user_id;not null;index:idx_user_profiles_user_id,priority:1;comment:用户id" json:"user_id"` // 用户id
	InvitationCode string    `gorm:"column:invitation_code;not null;comment:用户的邀请码" json:"invitation_code"`                          // 用户的邀请码
	WalletAddress  string    `gorm:"column:wallet_address;not null;comment:用户的钱包地址" json:"wallet_address"`                           // 用户的钱包地址
	Realname       string    `gorm:"column:realname;not null;comment:真实姓名" json:"realname"`                                          // 真实姓名
	Nickname       string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                            // 昵称
	Avatar         string    `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                                                // 头像
	Gender         int8     `gorm:"column:gender;not null;default:3;comment:性别：1-男；2-女；3-未知" json:"gender"`                         // 性别：1-男；2-女；3-未知
	Birthday       time.Time `gorm:"column:birthday;comment:出生日期" json:"birthday"`                                                   // 出生日期
	Phone          string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                                 // 手机号
	Email          string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                                  // 邮箱
	GauthPass      string    `gorm:"column:gauth_pass;not null;comment:谷歌验证" json:"gauth_pass"`                                      // 谷歌验证
	Question       string    `gorm:"column:question;not null;comment:密保问题" json:"question"`                                          // 密保问题
	GauthSecret    string    `gorm:"column:gauth_secret;not null;comment:谷歌验证密钥" json:"gauth_secret"`                                // 谷歌验证密钥
	GauthStatus    int8     `gorm:"column:gauth_status;not null;default:2;comment:谷歌验证启用状态：1-启用；2-禁用" json:"gauth_status"`          // 谷歌验证启用状态：1-启用；2-禁用
	//
	gormx.Model
}

// TableName UserProfile's table name
func (*UserProfile) TableName() string {
	return TableNameUserProfile
}
