// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID               int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                                                 // 主键
	UserID           int64  `gorm:"column:user_id;not null;uniqueIndex:idx_users_user_id,priority:1;comment:用户id" json:"user_id"`                                                 // 用户id
	Pid              int64  `gorm:"column:pid;not null;index:idx_users_pid,priority:1;comment:上级id（邀请用户的ID）" json:"pid"`                                                          // 上级id（邀请用户的ID）
	Username         string `gorm:"column:username;not null;comment:账号" json:"username"`                                                                                          // 账号
	Password         string `gorm:"column:password;not null;comment:密码" json:"password"`                                                                                          // 密码
	LanguageCode     string `gorm:"column:language_code;not null;comment:语言code" json:"language_code"`                                                                            // 语言code
	CurrencyCode     string `gorm:"column:currency_code;not null;comment:币种code" json:"currency_code"`                                                                            // 币种code
	VipLevelID       int64  `gorm:"column:vip_level_id;not null;default:1;comment:会员等级id（user_vip_levels的id）" json:"vip_level_id"`                                                // 会员等级id（user_vip_levels的id）
	WithdrawPassword string `gorm:"column:withdraw_password;not null;comment:提现密码" json:"withdraw_password"`                                                                      // 提现密码
	Remark           string `gorm:"column:remark;not null;comment:备注" json:"remark"`                                                                                              // 备注
	Status           int8   `gorm:"column:status;not null;index:idx_users_status,priority:1;default:1;comment:用户状态：1-正常；2-手动冻结；3-异常冻结；4-禁止领取优惠；5-禁止提现；6-黑名单；7-停用；" json:"status"` // 用户状态：1-正常；2-手动冻结；3-异常冻结；4-禁止领取优惠；5-禁止提现；6-黑名单；7-停用；
	LastLoginTime    int64  `gorm:"column:last_login_time;not null;index:idx_users_last_login_time,priority:1;comment:最后登录时间" json:"last_login_time"`                             // 最后登录时间
	//
	gormx.Model
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
