// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameUserTag = "user_tags"

// UserTag mapped from table <user_tags>
type UserTag struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键，唯一标识每个标签" json:"id"`     // 自增主键，唯一标识每个标签
	UserID        int64  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                         // 用户ID
	TagID         int64  `gorm:"column:tag_id;not null;comment:标签ID" json:"tag_id"`                           // 标签ID
	//
	gormx.OperationBaseModel
	gormx.Model
}

// TableName UserTag's table name
func (*UserTag) TableName() string {
	return TableNameUserTag
}
