// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameUserWallet = "user_wallets"

// UserWallet mapped from table <user_wallets>
type UserWallet struct {
	ID            int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                // 主键ID
	WalletType    int8 `gorm:"column:wallet_type;not null;comment:钱包类型：1-用户钱包，2-代理钱包，3-奖励钱包，4-USDT钱包" json:"wallet_type"`     // 钱包类型：1-用户钱包，2-代理钱包，3-奖励钱包，4-USDT钱包
	UserID        int64 `gorm:"column:user_id;not null;index:idx_user_wallets_user_id,priority:1;comment:用户ID" json:"user_id"` // 用户ID
	Balance       int64 `gorm:"column:balance;not null;comment:可用余额" json:"balance"`                                           // 可用余额
	LockedBalance int64 `gorm:"column:locked_balance;not null;comment:锁定余额" json:"locked_balance"`                             // 锁定余额
	Status        int8 `gorm:"column:status;not null;default:1;comment:状态：1-启用，2-禁用" json:"status"`                           // 状态：1-启用，2-禁用
	//
	gormx.Model
}

// TableName UserWallet's table name
func (*UserWallet) TableName() string {
	return TableNameUserWallet
}
