// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package pmodel

import "github.com/QuantumShiftX/golib/stores/gormx"

const TableNameUserFarm = "user_farms"

// UserFarm mapped from table <user_farms>
type UserFarm struct {
	ID                    int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                  // 主键ID
	UserID                int64  `gorm:"column:user_id;not null;index:idx_user_farms_user_id,priority:1;comment:用户ID" json:"user_id"`                     // 用户ID
	FarmName              string `gorm:"column:farm_name;not null;comment:农场名称" json:"farm_name"`                                                         // 农场名称
	TotalLandCount        int64  `gorm:"column:total_land_count;not null;default:20;comment:农场总土地数量" json:"total_land_count"`                             // 农场总土地数量
	WaterLimitPerDay      int64  `gorm:"column:water_limit_per_day;default:10;comment:每日浇水限制次数" json:"water_limit_per_day"`                               // 每日浇水限制次数
	FertilizerLimitPerDay int64  `gorm:"column:fertilizer_limit_per_day;default:1;comment:每日作物施肥限制次数（每个作物）" json:"fertilizer_limit_per_day"`              // 每日作物施肥限制次数（每个作物）
	TotalRewardCoins      int64  `gorm:"column:total_reward_coins;comment:农场总收益金币" json:"total_reward_coins"`                                             // 农场总收益金币
	HasReceivedFreeGift   int8  `gorm:"column:has_received_free_gift;not null;default:1;comment:是否已领取新用户免费商品：1-未领取，2-已领取" json:"has_received_free_gift"` // 是否已领取新用户免费商品：1-未领取，2-已领取
	HasCompletedTutorial  int8  `gorm:"column:has_completed_tutorial;not null;default:1;comment:是否已参加过新手教程：1-未参加，2-已参加" json:"has_completed_tutorial"`   // 是否已参加过新手教程：1-未参加，2-已参加
	//
	gormx.Model
}

// TableName UserFarm's table name
func (*UserFarm) TableName() string {
	return TableNameUserFarm
}
